# Trading Configuration
trading:
  # Default capital for backtesting
  initial_capital: 100000
  
  # Commission settings
  commission:
    rate: 0.001  # 0.1%
    per_share: false
  
  # Risk management
  risk:
    max_position_size: 0.1  # 10% of portfolio per position
    stop_loss: 0.02  # 2% stop loss
    take_profit: 0.06  # 6% take profit
    max_drawdown: 0.15  # 15% max drawdown

# Data Configuration
data:
  default_provider: "yahoo"
  cache_duration: 3600  # 1 hour in seconds
  
  yahoo:
    auto_adjust: true
    back_adjust: false
    
# Interactive Brokers Configuration
interactive_brokers:
  host: "127.0.0.1"
  port: 7497  # Paper trading port (7496 for live)
  client_id: 1
  timeout: 30
  
  # Paper trading settings
  paper_trading: true
  
# Logging Configuration
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name} | {message}"
  file: "logs/scizor.log"
  rotation: "1 day"
  retention: "30 days"

# Monitoring Configuration
monitoring:
  enable_dashboard: false
  dashboard_port: 8000
  enable_slack_notifications: false
  slack_webhook_url: ""

# Strategy Defaults
strategy:
  # Default lookback period for indicators
  lookback_period: 20
  
  # Rebalancing frequency
  rebalance_frequency: "daily"  # daily, weekly, monthly
