from sqlalchemy import Column, Integer, String, DECIMAL, DateTime, Text, Index
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.sql import func
from app.config.database import Base


class Signal(Base):
    """Trading signals generated by strategies"""
    __tablename__ = "signals"
    
    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String(10), nullable=False)
    strategy = Column(String(50), nullable=False)
    signal_type = Column(String(10), nullable=False)  # BUY, SELL, CLOSE
    price = Column(DECIMAL(12, 4), nullable=False)
    confidence = Column(DECIMAL(5, 4), nullable=False)
    signal_metadata = Column(JSONB)
    generated_at = Column(DateTime, nullable=False)
    executed_at = Column(DateTime)
    status = Column(String(20), default='PENDING')  # PENDING, EXECUTED, CANCELLED, EXPIRED
    created_at = Column(DateTime, default=func.current_timestamp())
    
    __table_args__ = (
        Index('idx_signals_symbol_generated', 'symbol', 'generated_at'),
        Index('idx_signals_status', 'status'),
        Index('idx_signals_strategy', 'strategy'),
    )